var _ = {
  ENV: "ENV",
  USER_INFO:"USER_INFO",
  LOGIN_INFO:"LOGIN_INFO",
  USER_AUTHORIZE:"USER_AUTHORIZE",
  SESSION_ID:"SESSION_ID",
  CUSTID:"CUSTID",
  USER_ID:"USER_ID",
  POSEQID:"POSEQID",
  AUTH_DATA:"AUTH_DATA",
  COOKIES:"COOKIES",
  TOKEN_KEY:"TOKEN_KEY"
}


module.exports = {
  STORAGE: _
};